heat_template_version: 2016-10-14

description: >
  Contrail Analytics service deployment using puppet, this YAML file
  creates the interface between the HOT template
  and the puppet manifest that actually installs
  and configures Contrail Analytics.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ContrailAnalyticsCollectorHttp:
    default: 8089
    description: Contrail Analytics Collector http port
    type: number
  ContrailAnalyticsCollectorSandesh:
    default: 8086
    description: Contrail Analytics Collector sandesh port
    type: number
  ContrailAnalyticsHttp:
    default: 8090
    description: Contrail Analytics http  port
    type: number
  ContrailAnalyticsRedis:
    default: 6379
    description: Contrail Analytics redis  port
    type: number
  ContrailAnalyticsApi:
    default: 8081
    description: Contrail Analytics Api  port
    type: number

resources:
  ContrailBase:
    type: ./contrail-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role Contrail Analytics using composable services.
    value:
      service_name: contrail_analytics
      config_settings:
        map_merge:
          - get_attr: [ContrailBase, role_data, config_settings]
          - contrail::analytics::collector_http_server_port: {get_param: ContrailAnalyticsCollectorHttp}
            contrail::analytics::collector_sandesh_port: {get_param: ContrailAnalyticsCollectorSandesh}
            contrail::analytics::host_ip: {get_param: [ServiceNetMap, ContrailAnalyticsNetwork]}
            contrail::analytics::http_server_port: {get_param: ContrailAnalyticsHttp}
            contrail::analytics::listen_ip_address: {get_param: [ServiceNetMap, ContrailAnalyticsNetwork]}
            contrail::analytics::redis_server: '127.0.0.1'
            contrail::analytics::redis_server_port: {get_param: ContrailAnalyticsRedis}
            contrail::analytics::rest_api_ip: {get_param: [ServiceNetMap, ContrailAnalyticsNetwork]}
            contrail::analytics::rest_api_port: {get_param: ContrailAnalyticsApi}
      step_config: |
        include ::tripleo::network::contrail::analytics
