heat_template_version: 2016-10-14

description: >
  Contrail Analytics Database service deployment using puppet, this YAML file
  creates the interface between the HOT template
  and the puppet manifest that actually installs
  and configures Contrail Analytics Database.

parameters:
  ServiceNetMap:
    type: json
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
  DefaultPasswords:
    type: json
    default: {}
  EndpointMap:
    type: json
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
  ContrailAnalyticsDBMinDiskGB:
    description:  The min size for Contrail Analytics DB.
                  It is to check the size of the node.
                  Contrail will fail installation if disk size is not enough.
    type: string
    default: ''

conditions:
  contrail_analyticsdb_min_disk_gb_unset: {equals : [{get_param: ContrailAnalyticsDBMinDiskGB}, '']}

resources:
  ContrailBase:
    type: ./contrail-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role Contrail Analytics Database using composable services.
    value:
      service_name: contrail_analytics_database
      config_settings:
        map_merge:
        - get_attr: [ContrailBase, role_data, config_settings]
        - contrail::analytics::database::host_ip: {get_param: [ServiceNetMap, ContrailAnalyticsDatabaseNetwork]}
        - if:
          - contrail_analyticsdb_min_disk_gb_unset
          - {}
          - contrail_analyticsdb_min_disk_gb: {get_param: ContrailAnalyticsDBMinDiskGB}
      step_config: |
        include ::tripleo::network::contrail::analyticsdatabase
